name: Trivy
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Scan IAC with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@latest
        with:
          cache: true
          version: v0.57.1

      #- name: Build an image from Dockerfile
       # run: docker build -t docker.io/my-organization/my-app:$#{{ github.sha }} .

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          skip-setup-trivy: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@latest
        with:
          sarif_file: "trivy-results.sarif"
