name: Tfsec 

on:
  push:
    branches: main
  pull_request: 
    branches: main
  workflow_dispatch:

jobs:
    tfsec:
        name: tfsec PR commenter
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write

        steps:
          - name: Clone repo
            uses: actions/checkout@master

          - name: tfsec
            uses: aquasecurity/tfsec-action@v1.0.0
            with:
              version: latest
              format: sarif
              working_directory: .
              soft_fail: true
            
          # - name: tfsec
          #   uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
          #   with:
          #       github_token: ${{ github.token }}
          #       tfsec_formats: sarif,json
